# Generated by Django 4.0.1 on 2022-01-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('place_of_birth', models.CharField(max_length=50)),
                ('relatives', models.TextField()),
                ('secret_information', models.TextField()),
                ('surgeries', models.TextField()),
                ('treating_doctor', models.CharField(max_length=250)),
                ('medical_treatment', models.TextField()),
            ],
        ),
    ]
