# Generated by Django 4.0.1 on 2022-01-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='medical_treatment',
            new_name='medecin_traitant',
        ),
    ]
