# Generated by Django 4.0.1 on 2022-01-31 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_medecin_traitant_resident_medical_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
