# Generated by Django 4.0.1 on 2022-02-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_resident_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='resident_pics'),
        ),
    ]
