# Generated by Django 4.0.1 on 2022-02-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_options_alter_resident_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relative',
            name='residents',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='relatives',
        ),
        migrations.AddField(
            model_name='resident',
            name='relatives',
            field=models.ManyToManyField(to='users.Relative'),
        ),
    ]
