# Generated by Django 4.0.1 on 2022-02-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_resident_relatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='relatives',
        ),
    ]
