# Generated by Django 4.0.1 on 2022-02-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_resident_relatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='relatives',
        ),
        migrations.AddField(
            model_name='relative',
            name='relatives',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.resident'),
        ),
    ]
