# Generated by Django 4.0.1 on 2022-02-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_relative_relatives_relative_relatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='adresse', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='Numéro de téléphone', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='relatives',
            field=models.ManyToManyField(to='users.Resident'),
        ),
        migrations.DeleteModel(
            name='Relative',
        ),
    ]
