# Generated by Django 4.0.1 on 2022-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_address_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('1', 'employee'), ('2', 'relative')], default='1', max_length=2),
        ),
    ]
