# Generated by Django 4.0.1 on 2022-02-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('employee', 'employee'), ('relative', 'relative')], default='1', max_length=20),
        ),
    ]
