# Generated by Django 4.0.1 on 2022-02-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
