# Generated by Django 4.0.1 on 2022-02-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Pas renseigné', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='Pas renseigné', max_length=40),
        ),
        migrations.AlterField(
            model_name='resident',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
    ]
