# Generated by Django 4.0.1 on 2022-02-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('1', 'employee'), ('2', 'relative')], default='2', max_length=20),
        ),
    ]
