# Generated by Django 4.0.1 on 2022-02-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='relatives',
            field=models.TextField(default='Pas de proches'),
        ),
    ]
