# Generated by Django 4.0.1 on 2022-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_resident_relatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='activities',
            field=models.TextField(default='Pas inscrit aux activités'),
        ),
        migrations.AddField(
            model_name='resident',
            name='floor',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='material',
            field=models.TextField(default='Pas de matériels'),
        ),
        migrations.AddField(
            model_name='resident',
            name='room_number',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
