# Generated by Django 4.0.1 on 2022-02-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_post_resident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date']},
        ),
    ]
